<?php  
 define('GLOBAL_NIGHT_CHARGE_START_TIME','2016-08-02'); 
 define('GLOBAL_NIGHT_CHARGE_START_TIMER','08:35:00'); 
 define('GLOBAL_NIGHT_CHARGE_END_TIME','2016-08-02'); 
 define('GLOBAL_NIGHT_CHARGE_END_TIMER','12:20:00'); 
 define('GLOBAL_PEAK_CHARGE_START_TIME','2016-08-02'); 
 define('GLOBAL_PEAK_CHARGE_START_TIMER','08:05:00'); 
 define('GLOBAL_PEAK_CHARGE_END_TIME','2016-08-02'); 
 define('GLOBAL_PEAK_CHARGE_END_TIMER','14:20:00'); 
 define('GLOBAL_TYPE_COMMISSION','P'); 
 define('GLOBAL_VARIABLE_TYPE_COMMISSION','F'); 
 define('GLOBAL_COMMISSION','5'); 
 define('GLOBAL_MIN_AMOUNT_FIX_COMMISSION','50'); 
 define('GLOBAL_INVOICE_DURATION','5'); 
 define('GLOBAL_REMITTED_DAYS','2'); 
 define('GLOBAL_VARIABLE_COMMISSION','10'); 
 define('GLOBAL_DISPATCH_TIME','20'); 
 define('GLOBAL_CANCEL_TIME','3'); 
 define('GLOBAL_IS_PEAK_CHARGE','N'); 
 define('GLOBAL_IS_NIGHT_CHARGE','Y'); 
 define('GLOBAL_CREATED','2016-01-14 01:56:25'); 
 define('GLOBAL_MODIFIED','2017-05-12 11:11:51'); 
 define('GLOBAL_SERVICE_FEE','1.5'); 
 define('SITE_EMAIL','info@roooz.com'); 
 //define('SITE_TITLE','Roooz'); 
 define('SITE_COPYRIGHT_TEXT','Copyright © 2017 Roooz.com.au'); 
 define('SITE_FB_URL','https://www.facebook.com/roooz'); 
 define('SITE_TWITTER_URL',''); 
 define('SITE_CONTACT','Australia'); 
 define('SITE_CALL','+618909898'); 
 define('SITE_GPLUS','https://plus.google.com/b/roooz'); 
 define('SITE_YOUTUBE_URL',''); 
 define('SITE_DISTANCE','50'); 
 define('SITE_NO_OF_DRIVER','10'); 
 ?>
